### ISSUE TITLE
Feat: allow taking from last built hart to be installed

### ISSUE THREAD

**Issue by bdangit** [test-kitchen/kitchen-habitat#7]
It would be nice to just specify `package_origin` and `package_name`, and kitchen should first look inside results folder for a previously built `.hart` before committing to going to the depot for installation.  

Currently in order to do any local testing without deploying to the depot, I need to specify the entire `artifact_name` down to the version and release.  This makes it hard to do complete local testing before deploying artifact into "public".

**Comment by bdangit** [comment]
looking through the code, i think an option maybe to specify a flag for `search_local_artifact: true/false` and augment to this [function](https://github.com/test-kitchen/kitchen-habitat/blob/master/lib/kitchen/provisioner/habitat.rb#L196) with a regex match to get the latest built hart.

**Comment by mhedgpeth** [comment]
Also it would be nice if the build were a part of the kitchen run. So your workflow would be: do some code, run kitchen, do some code, run kitchen & it would build it for you (maybe as a part of the "converge"?)

**Comment by bdangit** [comment]
That would be very ideal! 👍

**Comment by bdangit** [comment]
started work to get this in, but looks like I'll need to figure out how to consistently "scp" or mount the results folder inside the instance each time.  Otherwise would need to destroy the instance and converge again.

**Comment by smurawski** [comment]
I've considered adding the build step.  I would take a PR on it, but I don't think I'll put the time into it at the moment.

**Comment by bdangit** [comment]
submitted #9

**Comment by bdangit** [comment]
adding the build step into the kitchen-habitat will be reserved for another time.

**Comment by smurawski** [comment]
closed via #9
